-- MySQL Script generated by MySQL Workbench
-- Fri Oct  2 16:25:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema negra_visao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema negra_visao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `negra_visao` DEFAULT CHARACTER SET utf8 ;
USE `negra_visao` ;

-- -----------------------------------------------------
-- Table `negra_visao`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nm_pessoa` VARCHAR(150) NOT NULL,
  `nr_cpf` CHAR(11) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `ds_email` VARCHAR(255) NULL,
  `nr_telefone` VARCHAR(11) NULL,
  `st_pessoa` ENUM('ATIVA', 'INATIVA') NOT NULL DEFAULT 'ATIVA',
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX `id_pessoa_UNIQUE` (`id_pessoa` ASC) ,
  UNIQUE INDEX `nr_cpf_UNIQUE` (`nr_cpf` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negra_visao`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `nr_cep` CHAR(8) NOT NULL,
  `ds_logradouro` VARCHAR(255) NOT NULL,
  `nr_imovel` VARCHAR(10) NOT NULL,
  `ds_complemento` VARCHAR(100) NULL DEFAULT NULL,
  `ds_bairro` VARCHAR(100) NOT NULL,
  `ds_municipio` VARCHAR(100) NOT NULL,
  `sg_uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`id_endereco`),
  UNIQUE INDEX `id_endereco_UNIQUE` (`id_endereco` ASC) ,
  INDEX `fk_endereco_pessoa_idx` (`id_pessoa` ASC) ,
  UNIQUE INDEX `id_pessoa_UNIQUE` (`id_pessoa` ASC) ,
  CONSTRAINT `fk_endereco_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `negra_visao`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negra_visao`.`papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`papel` (
  `id_papel` INT NOT NULL AUTO_INCREMENT,
  `nm_papel` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_papel`),
  UNIQUE INDEX `id_papel_UNIQUE` (`id_papel` ASC) ,
  UNIQUE INDEX `nm_papel_UNIQUE` (`nm_papel` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negra_visao`.`usuarioInterno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`usuarioInterno` (
  `id_usuarioInterno` INT NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `nm_login` VARCHAR(100) NOT NULL,
  `nm_senha` VARCHAR(255) NOT NULL,
  `st_situacao_acesso` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
  PRIMARY KEY (`id_usuarioInterno`),
  UNIQUE INDEX `id_usuarioInterno_UNIQUE` (`id_usuarioInterno` ASC) ,
  INDEX `fk_usuarioInterno_pessoa1_idx` (`id_pessoa` ASC) ,
  UNIQUE INDEX `nm_login_UNIQUE` (`nm_login` ASC) ,
  UNIQUE INDEX `id_pessoa_UNIQUE` (`id_pessoa` ASC) ,
  CONSTRAINT `fk_usuarioInterno_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `negra_visao`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negra_visao`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `ds_titulo` VARCHAR(150) NOT NULL,
  `ds_evento` TEXT NOT NULL,
  `tp_evento` ENUM('CURSO', 'OFICINA', 'PALESTRA') NOT NULL,
  `ds_local` VARCHAR(255) NOT NULL,
  `st_classificacao` ENUM('UNICO', 'RECORRENTE') NOT NULL,
  `st_frequencia` ENUM('DIARIA', 'SEMANAL', 'QUINZENAL', 'MENSAL') NULL,
  `ds_modalidade_duracao` ENUM('QUANTIDADE_OCORRENCIAS', 'DATA_FINAL', 'SEM_PREVISAO_DE_FIM') NULL,
  `nr_quantidade_total_ocorrencias` INT UNSIGNED NULL,
  `dt_final` DATE NULL,
  `nr_capacidade` INT UNSIGNED NOT NULL,
  `dt_hora_abertura_inscricao` DATETIME NOT NULL,
  `dt_hora_encerramento_inscricao` DATETIME NULL,
  `nr_limite_faltas_consecutivas` INT UNSIGNED NULL,
  `st_estado_evento` ENUM('PROGRAMADO', 'REALIZADO', 'CANCELADO') NOT NULL,
  `st_visibilidade` ENUM('OCULTO', 'PUBLICADO') NOT NULL DEFAULT 'OCULTO',
  `ds_motivo_cancelamento` VARCHAR(255) NULL,
  PRIMARY KEY (`id_evento`),
  UNIQUE INDEX `id_evento_UNIQUE` (`id_evento` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negra_visao`.`ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`ocorrencia` (
  `id_ocorrencia` INT NOT NULL AUTO_INCREMENT,
  `id_evento` INT NOT NULL,
  `dt_hora_inicio` DATETIME NOT NULL,
  `dt_hora_fim` DATETIME NOT NULL,
  `st_cancelada` TINYINT(1) NOT NULL DEFAULT 0,
  `st_lista_presenca_finalizada` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_ocorrencia`),
  INDEX `fk_ocorrencia_evento1_idx` (`id_evento` ASC) ,
  CONSTRAINT `fk_ocorrencia_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `negra_visao`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negra_visao`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`responsavel` (
  `id_responsavel` INT NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `ds_responsavel` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_responsavel`),
  INDEX `fk_responsavel_pessoa1_idx` (`id_pessoa` ASC) ,
  UNIQUE INDEX `id_responsavel_UNIQUE` (`id_responsavel` ASC) ,
  UNIQUE INDEX `id_pessoa_UNIQUE` (`id_pessoa` ASC) ,
  CONSTRAINT `fk_responsavel_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `negra_visao`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negra_visao`.`evento_responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`evento_responsavel` (
  `id_evento` INT NOT NULL,
  `id_responsavel` INT NOT NULL,
  PRIMARY KEY (`id_evento`, `id_responsavel`),
  INDEX `fk_evento_responsavel_responsavel1_idx` (`id_responsavel` ASC) ,
  CONSTRAINT `fk_evento_responsavel_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `negra_visao`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_responsavel_responsavel1`
    FOREIGN KEY (`id_responsavel`)
    REFERENCES `negra_visao`.`responsavel` (`id_responsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negra_visao`.`inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`inscricao` (
  `id_inscricao` INT NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `id_evento` INT NOT NULL,
  `cd_inscricao` VARCHAR(50) NOT NULL,
  `st_estado` ENUM('CONFIRMADA', 'INVALIDADA_POR_INATIVACAO', 'CANCELADA_POR_EVENTO', 'CANCELADA_A_PEDIDO', 'ENCERRADA_POR_FALTAS') NOT NULL DEFAULT 'CONFIRMADA',
  `ds_motivo_cancelamento` VARCHAR(255) NULL DEFAULT NULL,
  `nr_faltas_consecutivas` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_inscricao`),
  UNIQUE INDEX `cd_inscricao_UNIQUE` (`cd_inscricao` ASC) ,
  INDEX `fk_inscricao_pessoa1_idx` (`id_pessoa` ASC) ,
  INDEX `fk_inscricao_evento1_idx` (`id_evento` ASC) ,
  UNIQUE INDEX `id_inscricao_UNIQUE` (`id_inscricao` ASC) ,
  UNIQUE INDEX `uq_inscricao_pessoa_evento` (`id_pessoa` ASC, `id_evento` ASC) ,
  CONSTRAINT `fk_inscricao_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `negra_visao`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricao_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `negra_visao`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negra_visao`.`presenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`presenca` (
  `id_presenca` INT NOT NULL AUTO_INCREMENT,
  `id_inscricao` INT NOT NULL,
  `id_ocorrencia` INT NOT NULL,
  `st_situacao_presenca` ENUM('PRESENTE', 'FALTA') NOT NULL,
  PRIMARY KEY (`id_presenca`),
  INDEX `fk_presenca_inscricao1_idx` (`id_inscricao` ASC) ,
  INDEX `fk_presenca_ocorrencia1_idx` (`id_ocorrencia` ASC) ,
  UNIQUE INDEX `uq_presenca_inscricao_ocorrencia` (`id_inscricao` ASC, `id_ocorrencia` ASC) ,
  CONSTRAINT `fk_presenca_inscricao1`
    FOREIGN KEY (`id_inscricao`)
    REFERENCES `negra_visao`.`inscricao` (`id_inscricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presenca_ocorrencia1`
    FOREIGN KEY (`id_ocorrencia`)
    REFERENCES `negra_visao`.`ocorrencia` (`id_ocorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negra_visao`.`pessoa_papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negra_visao`.`pessoa_papel` (
  `id_pessoa` INT NOT NULL,
  `id_papel` INT NOT NULL,
  PRIMARY KEY (`id_pessoa`, `id_papel`),
  INDEX `fk_pessoa_papel_papel1_idx` (`id_papel` ASC) ,
  CONSTRAINT `fk_pessoa_papel_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `negra_visao`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_papel_papel1`
    FOREIGN KEY (`id_papel`)
    REFERENCES `negra_visao`.`papel` (`id_papel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
